# Generated by Django 5.2.9 on 2025-12-13 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(editable=False, null=True, verbose_name='updated at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=100, null=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.car')),
            ],
            options={
                'verbose_name': 'order',
                'db_table': 'm_orders',
            },
        ),
    ]
